<a href="https://colab.research.google.com/github/Vysokodelovoi/IAD_GP/blob/main/gp_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Построение моделей машинного обучения до FE. Классификация.

In [2]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 6.7 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [3]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.3 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [33]:
import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.svm import LinearSVC
from sklearn.metrics import f1_score
import catboost as cb
from catboost import CatBoostClassifier
import optuna
import mlutils as mu

In [5]:
df = pd.read_parquet('main_df_edited_no_dup.parquet')

In [6]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,country_full,arrival_date_month_num
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01,Portugal,6
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01,Portugal,6
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02,United Kingdom,6
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02,United Kingdom,6
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,0,Transient,98.00,0,1,Check-Out,2015-07-03,United Kingdom,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118893,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,0,Transient,96.14,0,0,Check-Out,2017-09-06,Belgium,7
118894,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,0,Transient,225.43,0,2,Check-Out,2017-09-07,France,7
118895,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,0,Transient,157.71,0,4,Check-Out,2017-09-07,Germany,7
118896,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,0,Transient,104.40,0,0,Check-Out,2017-09-07,United Kingdom,7
118897,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,0,Transient,151.20,0,2,Check-Out,2017-09-07,Germany,7

In [7]:
# Линейные модели logistic_regression / linear, Даниэль
#  svm Игорь
#  boosting Игорь
#  random trees Даниэль
#  нейронка Игорь
#  изотоническая регрессия Даниэль
#  ранжирование попробовать? Игорь

#  Для каждой затюнить гиперпараметры через GridSearchCV или optuna
#  Результаты по проведенным экспериментам собрать в pandas датасет и отправить
#  Сделать выводы по performance моделю, посмотреть на важность признаков через shap или feature_importances


#  Графики с дубликатами и без сравнить

In [8]:
df_model = df[[c for c in df.columns if c not in ['reservation_status', 'reservation_status_date', 'country_full']]]

In [9]:
df_model

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,arrival_date_month_num
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,C,C,3,No Deposit,0,Transient,0.00,0,0,6
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,C,C,4,No Deposit,0,Transient,0.00,0,0,6
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,A,C,0,No Deposit,0,Transient,75.00,0,0,6
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,A,A,0,No Deposit,0,Transient,75.00,0,0,6
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,A,A,0,No Deposit,0,Transient,98.00,0,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118893,City Hotel,0,23,2017,August,35,30,2,5,2,...,A,A,0,No Deposit,0,Transient,96.14,0,0,7
118894,City Hotel,0,102,2017,August,35,31,2,5,3,...,E,E,0,No Deposit,0,Transient,225.43,0,2,7
118895,City Hotel,0,34,2017,August,35,31,2,5,2,...,D,D,0,No Deposit,0,Transient,157.71,0,4,7
118896,City Hotel,0,109,2017,August,35,31,2,5,2,...,A,A,0,No Deposit,0,Transient,104.40,0,0,7
118897,City Hotel,0,205,2017,August,35,29,2,7,2,...,A,A,0,No Deposit,0,Transient,151.20,0,2,7

In [10]:
X = df_model[[c for c in df_model.columns if c != 'is_canceled']].copy()
y = df_model.is_canceled.copy()

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=8)

## SVM

In [ ]:
num_features = [
    'lead_time', 'arrival_date_year', 'arrival_date_week_number',
    'arrival_date_day_of_month', 'stays_in_weekend_nights',
    'stays_in_week_nights', 'adults', 'children', 'babies',
    'is_repeated_guest', 'previous_cancellations',
    'previous_bookings_not_canceled', 'booking_changes',
    'days_in_waiting_list', 'required_car_parking_spaces',
    'total_of_special_requests'
]

cat_features = [
    'hotel', 'arrival_date_month', 'meal', 'country',
    'market_segment', 'distribution_channel', 'reserved_room_type',
    'assigned_room_type', 'deposit_type', 'customer_type'
]

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('scaler', StandardScaler(), num_features),
        ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), cat_features)
    ]
)

In [ ]:
svm_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('pca', PCA()),
    ('classifier', LinearSVC(dual=False, random_state=8)),
])

In [ ]:
def objective(trial):

    max_iter_param = trial.suggest_int('classifier__max_iter', 1000, 10000, step=1000)
    tol_param = trial.suggest_float('classifier__tol', 1e-5, 1e-2, log=True)
    c_param = trial.suggest_float('classifier__C', 1e-4, 1e2, log=True)

    scaler_param = trial.suggest_categorical('scaler_type', ['standard', 'robust'])
    scaler = StandardScaler() if scaler_param == 'standard' else RobustScaler()

    use_pca = trial.suggest_categorical('use_pca', [True, False])

    if use_pca:
        pca_components = trial.suggest_int('pca__n_components', 1, 35)
        pca_step = PCA(n_components=pca_components)
    else:
        pca_step = 'passthrough'

    svm_pipeline.set_params(
        preprocessor__scaler=scaler,
        pca=pca_step,
        classifier__C=c_param,
        classifier__max_iter=max_iter_param,
        classifier__tol=tol_param
    )

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=8)
    scores = cross_val_score(
        svm_pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring='f1',
        n_jobs=-1,
        error_score='raise'
    )
    return np.mean(scores)

In [ ]:
# study = optuna.create_study(direction='maximize')
# study.optimize(objective, show_progress_bar=True, n_trials=50)

# print("Лучшие параметры:", study.best_params)
# print("Лучший F1-score:", study.best_value)

In [ ]:
# best = study.best_params

In [ ]:
best = {'classifier__max_iter': 10000, 'classifier__tol': 0.0008743508260033666, 'classifier__C': 36.856060983954215, 'scaler_type': 'standard', 'use_pca': False}

best_scaler = StandardScaler() if best['scaler_type'] == 'standard' else RobustScaler()

if best.get('use_pca', False):
    best_pca = PCA(n_components=best['pca__n_components'])
else:
    best_pca = 'passthrough'

svm_pipeline.set_params(
    preprocessor__scaler=best_scaler,
    pca=best_pca,
    classifier__C=best['classifier__C'],
    classifier__max_iter=best['classifier__max_iter'],
    classifier__tol=best['classifier__tol']
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  ['lead_time',
                                                   'arrival_date_year',
                                                   'arrival_date_week_number',
                                                   'arrival_date_day_of_month',
                                                   'stays_in_weekend_nights',
                                                   'stays_in_week_nights',
                                                   'adults', 'children',
                                                   'babies',
                                                   'is_repeated_guest',
                                                   'previous_cancellations',
                                                   'previous_bookings_not_canceled',
                                                   'booking_change...
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['hotel',
                                                   'arrival_date_month', 'meal',
                                                   'country', 'market_segment',
                                                   'distribution_channel',
                                                   'reserved_room_type',
                                                   'assigned_room_type',
                                                   'deposit_type',
                                                   'customer_type'])])),
                ('pca', 'passthrough'),
                ('classifier',
                 LinearSVC(C=36.856060983954215, dual=False, max_iter=10000,
                           random_state=8, tol=0.0008743508260033666))])

In [ ]:
import importlib
import ml_utils as mu

# Эта команда принудительно обновит модуль в памяти Jupyter
importlib.reload(mu)

In [ ]:
mu.run_experiment(svm_pipeline, 'svm', 'main_df_edited_no_dup.parquet', best)

svm | score: 0.55317 time: 5.7s

/content/ml_utils.py:50: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, pd.DataFrame([result_row])], ignore_index=True)

{'timestamp': '2026-06-14T22:58:17.660727',
 'method': 'svm',
 'params': '{"classifier__max_iter": 10000, "classifier__tol": 0.0008743508260033666, "classifier__C": 36.856060983954215, "scaler_type": "standard", "use_pca": false}',
 'score': 0.553168880455408,
 'duration_sec': 5.713756799697876}

## CatBoost

In [ ]:
X = df_model[[c for c in df_model.columns if c not in ['is_canceled','country_full']]].copy()
y = df_model.is_canceled.copy()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=8)

In [ ]:
num_features = [
    'lead_time', 'arrival_date_year', 'arrival_date_week_number',
    'arrival_date_day_of_month', 'stays_in_weekend_nights',
    'stays_in_week_nights', 'adults', 'children', 'babies',
    'is_repeated_guest', 'previous_cancellations',
    'previous_bookings_not_canceled', 'booking_changes',
    'days_in_waiting_list', 'required_car_parking_spaces',
    'total_of_special_requests'
]

cat_features = [
    'hotel', 'arrival_date_month', 'meal', 'country',
    'market_segment', 'distribution_channel', 'reserved_room_type',
    'assigned_room_type', 'deposit_type', 'customer_type'
]

In [ ]:
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 200, 1000, step=100),
        'depth': trial.suggest_int('depth', 4, 6),
        'learning_rate': trial.suggest_float('learning_rate', 0.03, 0.2, log=True),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1e-2, 10.0, log=True),
        'cat_features': cat_features,
        'random_seed': 8,
        'thread_count': -1,
        'early_stopping_rounds': trial.suggest_int('early_stopping_rounds', 10, 100, step=5)
    }

    model = CatBoostClassifier(**params)

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=8)
    scores = []
    for train_idx, val_idx in cv.split(X_train, y_train):

        X_train_train = X_train.iloc[train_idx]
        X_train_val = X_train.iloc[val_idx]
        y_train_train = y_train.iloc[train_idx]
        y_train_val = y_train.iloc[val_idx]

        model = cb.CatBoostClassifier(**params)

        model.fit(
            X_train_train, y_train_train,
            eval_set=(X_train_val, y_train_val),
            verbose=False
        )

        y_pred = model.predict(X_train_val)
        scores.append(f1_score(y_train_val, y_pred))

    return np.mean(scores)

In [ ]:
study_cb = optuna.create_study(direction='maximize')
study_cb.optimize(objective, n_trials=50, show_progress_bar=True)

[I 2026-06-14 16:30:45,557] A new study created in memory with name: no-name-78b32a70-b284-4478-9fc9-28277e4a28d8

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-06-14 16:38:29,971] Trial 0 finished with value: 0.6886515832289016 and parameters: {'iterations': 1000, 'depth': 4, 'learning_rate': 0.05525117752762227, 'l2_leaf_reg': 0.9709957380220429, 'early_stopping_rounds': 85}. Best is trial 0 with value: 0.6886515832289016.
[I 2026-06-14 16:43:44,086] Trial 1 finished with value: 0.6787954117764385 and parameters: {'iterations': 700, 'depth': 4, 'learning_rate': 0.03656176676313291, 'l2_leaf_reg': 0.05305348598636522, 'early_stopping_rounds': 80}. Best is trial 0 with value: 0.6886515832289016.
[I 2026-06-14 16:50:41,822] Trial 2 finished with value: 0.6980778170816262 and parameters: {'iterations': 900, 'depth': 4, 'learning_rate': 0.15179953122208972, 'l2_leaf_reg': 0.02629742319435691, 'early_stopping_rounds': 85}. Best is trial 2 with value: 0.6980778170816262.
[I 2026-06-14 16:56:52,358] Trial 3 finished with value: 0.6930103966573767 and parameters: {'iterations': 1000, 'depth': 5, 'learning_rate': 0.06900829323089025, 'l2_leaf_reg': 0.08399050869848369, 'early_stopping_rounds': 10}. Best is trial 2 with value: 0.6980778170816262.
[I 2026-06-14 17:03:45,983] Trial 4 finished with value: 0.6895697859670701 and parameters: {'iterations': 600, 'depth': 6, 'learning_rate': 0.0336321448202872, 'l2_leaf_reg': 0.07634240550802586, 'early_stopping_rounds': 25}. Best is trial 2 with value: 0.6980778170816262.
[I 2026-06-14 17:12:22,737] Trial 5 finished with value: 0.696428956036152 and parameters: {'iterations': 1000, 'depth': 5, 'learning_rate': 0.08044940030486945, 'l2_leaf_reg': 4.45228375371053, 'early_stopping_rounds': 20}. Best is trial 2 with value: 0.6980778170816262.
[I 2026-06-14 17:14:38,366] Trial 6 finished with value: 0.6827739851438195 and parameters: {'iterations': 300, 'depth': 4, 'learning_rate': 0.0975701868896962, 'l2_leaf_reg': 0.022937224451067696, 'early_stopping_rounds': 100}. Best is trial 2 with value: 0.6980778170816262.
[I 2026-06-14 17:21:34,971] Trial 7 finished with value: 0.6940985683952983 and parameters: {'iterations': 900, 'depth': 4, 'learning_rate': 0.09341519779942524, 'l2_leaf_reg': 0.426206337910093, 'early_stopping_rounds': 30}. Best is trial 2 with value: 0.6980778170816262.
[I 2026-06-14 17:29:42,552] Trial 8 finished with value: 0.6939868547632446 and parameters: {'iterations': 700, 'depth': 6, 'learning_rate': 0.04575010895084481, 'l2_leaf_reg': 1.01529255622526, 'early_stopping_rounds': 40}. Best is trial 2 with value: 0.6980778170816262.
[I 2026-06-14 17:38:00,701] Trial 9 finished with value: 0.7009245639834374 and parameters: {'iterations': 700, 'depth': 6, 'learning_rate': 0.11286237091581697, 'l2_leaf_reg': 0.07417910057262825, 'early_stopping_rounds': 85}. Best is trial 9 with value: 0.7009245639834374.
[I 2026-06-14 17:39:53,888] Trial 10 finished with value: 0.6895482040939642 and parameters: {'iterations': 200, 'depth': 5, 'learning_rate': 0.19714533199357723, 'l2_leaf_reg': 8.456776010977556, 'early_stopping_rounds': 55}. Best is trial 9 with value: 0.7009245639834374.
[I 2026-06-14 17:45:23,438] Trial 11 finished with value: 0.6969736524463283 and parameters: {'iterations': 500, 'depth': 6, 'learning_rate': 0.148706133129074, 'l2_leaf_reg': 0.010836104497145676, 'early_stopping_rounds': 70}. Best is trial 9 with value: 0.7009245639834374.
[I 2026-06-14 17:53:12,291] Trial 12 finished with value: 0.7010260322619516 and parameters: {'iterations': 800, 'depth': 5, 'learning_rate': 0.1398336717868352, 'l2_leaf_reg': 0.2265442520413868, 'early_stopping_rounds': 100}. Best is trial 12 with value: 0.7010260322619516.
[I 2026-06-14 18:00:58,867] Trial 13 finished with value: 0.6992627863520466 and parameters: {'iterations': 800, 'depth': 5, 'learning_rate': 0.1184867316563817, 'l2_leaf_reg': 0.2713977764879048, 'early_stopping_rounds': 100}. Best is trial 12 with value: 0.7010260322619516.
[I 2026-06-14 18:06:50,936] Trial 14 finished with value: 0.6988765386609909 and parameters: {'iterations': 500, 'depth': 6, 'learning_rate': 0.12698878518448425, 'l2_leaf_reg': 0.21669360327334902, 'early_stopping_rounds': 65}. Best is trial 12 with value: 0.7010260322619516.
[I 2026-06-14 18:13:41,192] Trial 15 finished with value: 0.7002964828356021 and parameters: {'iterations': 700, 'depth': 5, 'learning_rate': 0.1901257182528244, 'l2_leaf_reg': 0.1318063432432389, 'early_stopping_rounds': 95}. Best is trial 12 with value: 0.7010260322619516.
[I 2026-06-14 18:19:32,368] Trial 16 finished with value: 0.6989236596673195 and parameters: {'iterations': 500, 'depth': 6, 'learning_rate': 0.11209752644870045, 'l2_leaf_reg': 0.5270404168675235, 'early_stopping_rounds': 75}. Best is trial 12 with value: 0.7010260322619516.
[I 2026-06-14 18:27:18,340] Trial 17 finished with value: 0.7008074574352866 and parameters: {'iterations': 800, 'depth': 5, 'learning_rate': 0.15731249601546135, 'l2_leaf_reg': 1.7411484291632808, 'early_stopping_rounds': 60}. Best is trial 12 with value: 0.7010260322619516.
[I 2026-06-14 18:34:19,669] Trial 18 finished with value: 0.6961577718367937 and parameters: {'iterations': 600, 'depth': 6, 'learning_rate': 0.06963835631604234, 'l2_leaf_reg': 0.03056119474626564, 'early_stopping_rounds': 90}. Best is trial 12 with value: 0.7010260322619516.
[I 2026-06-14 18:42:04,158] Trial 19 finished with value: 0.6964983917944325 and parameters: {'iterations': 800, 'depth': 5, 'learning_rate': 0.09745308132579018, 'l2_leaf_reg': 0.17975286351053602, 'early_stopping_rounds': 50}. Best is trial 12 with value: 0.7010260322619516.
[I 2026-06-14 18:46:45,541] Trial 20 finished with value: 0.699182792602093 and parameters: {'iterations': 400, 'depth': 6, 'learning_rate': 0.13650785266205623, 'l2_leaf_reg': 0.047462564639993876, 'early_stopping_rounds': 75}. Best is trial 12 with value: 0.7010260322619516.
[W 2026-06-14 18:47:38,569] Trial 21 failed with parameters: {'iterations': 800, 'depth': 5, 'learning_rate': 0.15648036709292015, 'l2_leaf_reg': 2.3201029179836214, 'early_stopping_rounds': 60} because of the following error: KeyboardInterrupt('').
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_2038/1405596317.py", line 26, in objective
    model.fit(
  File "/usr/local/lib/python3.12/dist-packages/catboost/core.py", line 5547, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
  File "/usr/local/lib/python3.12/dist-packages/catboost/core.py", line 2716, in _fit
    self._train(
  File "/usr/local/lib/python3.12/dist-packages/catboost/core.py", line 1824, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5430, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5479, in _catboost._CatBoost._train
KeyboardInterrupt
[W 2026-06-14 18:47:38,576] Trial 21 failed with value None.

KeyboardInterrupt:

In [ ]:
best = {'iterations': 800, 'depth': 5, 'learning_rate': 0.1398336717868352, 'l2_leaf_reg': 0.2265442520413868, 'early_stopping_rounds': 100, 'cat_features': cat_features}

In [ ]:
import mlutils as mu

In [ ]:
cb_pipeline = CatBoostClassifier(**best)
mu.run_experiment(cb_pipeline, 'catboost', 'main_df_edited_no_dup.parquet', param_dict=best)

0:	learn: 0.6116590	total: 145ms	remaining: 1m 56s
1:	learn: 0.5702473	total: 254ms	remaining: 1m 41s
2:	learn: 0.5412556	total: 337ms	remaining: 1m 29s
3:	learn: 0.5123410	total: 418ms	remaining: 1m 23s
4:	learn: 0.4885666	total: 476ms	remaining: 1m 15s
5:	learn: 0.4716983	total: 535ms	remaining: 1m 10s
6:	learn: 0.4575741	total: 602ms	remaining: 1m 8s
7:	learn: 0.4466495	total: 666ms	remaining: 1m 5s
8:	learn: 0.4410961	total: 745ms	remaining: 1m 5s
9:	learn: 0.4356693	total: 823ms	remaining: 1m 5s
10:	learn: 0.4301783	total: 904ms	remaining: 1m 4s
11:	learn: 0.4266186	total: 982ms	remaining: 1m 4s
12:	learn: 0.4196575	total: 1.06s	remaining: 1m 4s
13:	learn: 0.4156020	total: 1.13s	remaining: 1m 3s
14:	learn: 0.4128498	total: 1.21s	remaining: 1m 3s
15:	learn: 0.4097617	total: 1.28s	remaining: 1m 2s
16:	learn: 0.4080068	total: 1.36s	remaining: 1m 2s
17:	learn: 0.4062892	total: 1.44s	remaining: 1m 2s
18:	learn: 0.4051317	total: 1.5s	remaining: 1m 1s
19:	learn: 0.4018052	total: 1.59s	remaining: 1m 1s
20:	learn: 0.3985048	total: 1.66s	remaining: 1m 1s
21:	learn: 0.3949720	total: 1.74s	remaining: 1m 1s
22:	learn: 0.3927119	total: 1.82s	remaining: 1m 1s
23:	learn: 0.3916815	total: 1.9s	remaining: 1m 1s
24:	learn: 0.3897207	total: 1.96s	remaining: 1m
25:	learn: 0.3888139	total: 2.02s	remaining: 1m
26:	learn: 0.3877138	total: 2.09s	remaining: 60s
27:	learn: 0.3857599	total: 2.17s	remaining: 60s
28:	learn: 0.3849708	total: 2.25s	remaining: 59.7s
29:	learn: 0.3829777	total: 2.34s	remaining: 60s
30:	learn: 0.3816585	total: 2.43s	remaining: 1m
31:	learn: 0.3803334	total: 2.49s	remaining: 59.7s
32:	learn: 0.3797192	total: 2.57s	remaining: 59.8s
33:	learn: 0.3794630	total: 2.65s	remaining: 59.7s
34:	learn: 0.3782952	total: 2.72s	remaining: 59.4s
35:	learn: 0.3775272	total: 2.8s	remaining: 59.4s
36:	learn: 0.3767977	total: 2.88s	remaining: 59.4s
37:	learn: 0.3762895	total: 2.94s	remaining: 58.9s
38:	learn: 0.3750821	total: 3.01s	remaining: 58.7s
39:	learn: 0.3747981	total: 3.08s	remaining: 58.6s
40:	learn: 0.3738754	total: 3.17s	remaining: 58.6s
41:	learn: 0.3732581	total: 3.24s	remaining: 58.5s
42:	learn: 0.3724844	total: 3.31s	remaining: 58.3s
43:	learn: 0.3719146	total: 3.38s	remaining: 58.2s
44:	learn: 0.3710592	total: 3.46s	remaining: 58.1s
45:	learn: 0.3707324	total: 3.53s	remaining: 57.9s
46:	learn: 0.3703696	total: 3.6s	remaining: 57.7s
47:	learn: 0.3698390	total: 3.68s	remaining: 57.7s
48:	learn: 0.3689136	total: 3.76s	remaining: 57.6s
49:	learn: 0.3686410	total: 3.81s	remaining: 57.2s
50:	learn: 0.3682724	total: 3.89s	remaining: 57.1s
51:	learn: 0.3678318	total: 3.96s	remaining: 57s
52:	learn: 0.3664984	total: 4.03s	remaining: 56.8s
53:	learn: 0.3661800	total: 4.1s	remaining: 56.6s
54:	learn: 0.3660277	total: 4.17s	remaining: 56.4s
55:	learn: 0.3652174	total: 4.24s	remaining: 56.3s
56:	learn: 0.3647627	total: 4.3s	remaining: 56.1s
57:	learn: 0.3645491	total: 4.38s	remaining: 56s
58:	learn: 0.3644226	total: 4.46s	remaining: 56s
59:	learn: 0.3641994	total: 4.53s	remaining: 55.9s
60:	learn: 0.3639494	total: 4.61s	remaining: 55.8s
61:	learn: 0.3636074	total: 4.67s	remaining: 55.6s
62:	learn: 0.3632298	total: 4.74s	remaining: 55.5s
63:	learn: 0.3628643	total: 4.82s	remaining: 55.4s
64:	learn: 0.3625117	total: 4.89s	remaining: 55.3s
65:	learn: 0.3624011	total: 4.96s	remaining: 55.2s
66:	learn: 0.3619089	total: 5.03s	remaining: 55s
67:	learn: 0.3617299	total: 5.1s	remaining: 54.9s
68:	learn: 0.3609370	total: 5.15s	remaining: 54.6s
69:	learn: 0.3607588	total: 5.22s	remaining: 54.4s
70:	learn: 0.3604629	total: 5.29s	remaining: 54.4s
71:	learn: 0.3602398	total: 5.37s	remaining: 54.3s
72:	learn: 0.3600147	total: 5.44s	remaining: 54.2s
73:	learn: 0.3596979	total: 5.51s	remaining: 54s
74:	learn: 0.3591613	total: 5.57s	remaining: 53.9s
75:	learn: 0.3588113	total: 5.65s	remaining: 53.8s
76:	learn: 0.3584913	total: 5.72s	remaining: 53.7s
77:	learn: 0.3582572	total: 5.79s	remaining: 53.6s
78:	learn: 0.3580438	total: 5.86s	remaining: 53.5s
79:	learn: 0.3577285	total: 5.93s	remaining: 53.4s
80:	learn: 0.3573730	total: 6s	remaining: 53.2s
81:	learn: 0.3570680	total: 6.07s	remaining: 53.1s
82:	learn: 0.3567773	total: 6.13s	remaining: 52.9s
83:	learn: 0.3565916	total: 6.19s	remaining: 52.7s
84:	learn: 0.3563155	total: 6.26s	remaining: 52.7s
85:	learn: 0.3562360	total: 6.33s	remaining: 52.5s
86:	learn: 0.3560649	total: 6.4s	remaining: 52.5s
87:	learn: 0.3557158	total: 6.49s	remaining: 52.5s
88:	learn: 0.3550702	total: 6.56s	remaining: 52.4s
89:	learn: 0.3546707	total: 6.63s	remaining: 52.3s
90:	learn: 0.3543292	total: 6.71s	remaining: 52.3s
91:	learn: 0.3540561	total: 6.79s	remaining: 52.2s
92:	learn: 0.3537693	total: 6.87s	remaining: 52.2s
93:	learn: 0.3534911	total: 6.94s	remaining: 52.2s
94:	learn: 0.3531148	total: 7.06s	remaining: 52.4s
95:	learn: 0.3528378	total: 7.17s	remaining: 52.6s
96:	learn: 0.3525165	total: 7.28s	remaining: 52.7s
97:	learn: 0.3522875	total: 7.41s	remaining: 53.1s
98:	learn: 0.3521087	total: 7.55s	remaining: 53.5s
99:	learn: 0.3516950	total: 7.67s	remaining: 53.7s
100:	learn: 0.3515415	total: 7.79s	remaining: 53.9s
101:	learn: 0.3510694	total: 7.92s	remaining: 54.2s
102:	learn: 0.3508546	total: 8.04s	remaining: 54.4s
103:	learn: 0.3507704	total: 8.17s	remaining: 54.7s
104:	learn: 0.3505398	total: 8.3s	remaining: 54.9s
105:	learn: 0.3500595	total: 8.41s	remaining: 55.1s
106:	learn: 0.3497081	total: 8.48s	remaining: 55s
107:	learn: 0.3495780	total: 8.56s	remaining: 54.8s
108:	learn: 0.3494507	total: 8.64s	remaining: 54.7s
109:	learn: 0.3492529	total: 8.71s	remaining: 54.7s
110:	learn: 0.3490223	total: 8.78s	remaining: 54.5s
111:	learn: 0.3488324	total: 8.85s	remaining: 54.4s
112:	learn: 0.3486786	total: 8.92s	remaining: 54.2s
113:	learn: 0.3484428	total: 8.99s	remaining: 54.1s
114:	learn: 0.3482576	total: 9.07s	remaining: 54s
115:	learn: 0.3480829	total: 9.14s	remaining: 53.9s
116:	learn: 0.3480069	total: 9.22s	remaining: 53.8s
117:	learn: 0.3478421	total: 9.29s	remaining: 53.7s
118:	learn: 0.3476412	total: 9.36s	remaining: 53.6s
119:	learn: 0.3474527	total: 9.44s	remaining: 53.5s
120:	learn: 0.3473212	total: 9.51s	remaining: 53.4s
121:	learn: 0.3470613	total: 9.57s	remaining: 53.2s
122:	learn: 0.3469277	total: 9.67s	remaining: 53.2s
123:	learn: 0.3466966	total: 9.75s	remaining: 53.1s
124:	learn: 0.3465326	total: 9.82s	remaining: 53s
125:	learn: 0.3463595	total: 9.88s	remaining: 52.8s
126:	learn: 0.3462342	total: 9.95s	remaining: 52.7s
127:	learn: 0.3461800	total: 10s	remaining: 52.6s
128:	learn: 0.3460413	total: 10.1s	remaining: 52.5s
129:	learn: 0.3458395	total: 10.2s	remaining: 52.4s
130:	learn: 0.3456364	total: 10.2s	remaining: 52.3s
131:	learn: 0.3455029	total: 10.3s	remaining: 52.2s
132:	learn: 0.3454450	total: 10.4s	remaining: 52.1s
133:	learn: 0.3453522	total: 10.5s	remaining: 52s
134:	learn: 0.3452544	total: 10.5s	remaining: 51.9s
135:	learn: 0.3451600	total: 10.6s	remaining: 51.7s
136:	learn: 0.3449374	total: 10.7s	remaining: 51.7s
137:	learn: 0.3448890	total: 10.8s	remaining: 51.6s
138:	learn: 0.3447124	total: 10.8s	remaining: 51.5s
139:	learn: 0.3446218	total: 10.9s	remaining: 51.5s
140:	learn: 0.3445811	total: 11s	remaining: 51.3s
141:	learn: 0.3443246	total: 11s	remaining: 51.2s
142:	learn: 0.3442883	total: 11.1s	remaining: 51.1s
143:	learn: 0.3440888	total: 11.2s	remaining: 50.9s
144:	learn: 0.3439273	total: 11.2s	remaining: 50.8s
145:	learn: 0.3438541	total: 11.3s	remaining: 50.6s
146:	learn: 0.3435508	total: 11.4s	remaining: 50.5s
147:	learn: 0.3434018	total: 11.4s	remaining: 50.4s
148:	learn: 0.3433282	total: 11.5s	remaining: 50.3s
149:	learn: 0.3431378	total: 11.6s	remaining: 50.2s
150:	learn: 0.3431025	total: 11.7s	remaining: 50.1s
151:	learn: 0.3429081	total: 11.7s	remaining: 50s
152:	learn: 0.3426598	total: 11.8s	remaining: 49.9s
153:	learn: 0.3425764	total: 11.9s	remaining: 49.8s
154:	learn: 0.3424208	total: 11.9s	remaining: 49.7s
155:	learn: 0.3422915	total: 12s	remaining: 49.6s
156:	learn: 0.3422225	total: 12.1s	remaining: 49.5s
157:	learn: 0.3417717	total: 12.2s	remaining: 49.4s
158:	learn: 0.3416107	total: 12.2s	remaining: 49.3s
159:	learn: 0.3414248	total: 12.3s	remaining: 49.2s
160:	learn: 0.3412762	total: 12.4s	remaining: 49.1s
161:	learn: 0.3411899	total: 12.4s	remaining: 49s
162:	learn: 0.3410174	total: 12.5s	remaining: 48.9s
163:	learn: 0.3408531	total: 12.6s	remaining: 48.8s
164:	learn: 0.3407982	total: 12.7s	remaining: 48.8s
165:	learn: 0.3407028	total: 12.8s	remaining: 48.8s
166:	learn: 0.3405424	total: 12.8s	remaining: 48.7s
167:	learn: 0.3402982	total: 12.9s	remaining: 48.6s
168:	learn: 0.3401924	total: 13s	remaining: 48.5s
169:	learn: 0.3401381	total: 13.1s	remaining: 48.4s
170:	learn: 0.3399934	total: 13.1s	remaining: 48.3s
171:	learn: 0.3398537	total: 13.2s	remaining: 48.2s
172:	learn: 0.3397354	total: 13.3s	remaining: 48.1s
173:	learn: 0.3396807	total: 13.3s	remaining: 48s
174:	learn: 0.3395314	total: 13.4s	remaining: 48s
175:	learn: 0.3394901	total: 13.5s	remaining: 47.9s
176:	learn: 0.3394250	total: 13.6s	remaining: 47.8s
177:	learn: 0.3393652	total: 13.7s	remaining: 47.8s
178:	learn: 0.3392821	total: 13.7s	remaining: 47.7s
179:	learn: 0.3391235	total: 13.8s	remaining: 47.6s
180:	learn: 0.3389317	total: 13.9s	remaining: 47.5s
181:	learn: 0.3387920	total: 14s	remaining: 47.5s
182:	learn: 0.3387418	total: 14s	remaining: 47.4s
183:	learn: 0.3385305	total: 14.1s	remaining: 47.2s
184:	learn: 0.3384876	total: 14.2s	remaining: 47.1s
185:	learn: 0.3384160	total: 14.3s	remaining: 47.1s
186:	learn: 0.3383869	total: 14.3s	remaining: 46.9s
187:	learn: 0.3382633	total: 14.4s	remaining: 46.8s
188:	learn: 0.3379226	total: 14.5s	remaining: 46.7s
189:	learn: 0.3378530	total: 14.5s	remaining: 46.6s
190:	learn: 0.3375800	total: 14.6s	remaining: 46.5s
191:	learn: 0.3374756	total: 14.7s	remaining: 46.5s
192:	learn: 0.3374467	total: 14.7s	remaining: 46.3s
193:	learn: 0.3373010	total: 14.8s	remaining: 46.3s
194:	learn: 0.3372054	total: 14.9s	remaining: 46.3s
195:	learn: 0.3370798	total: 15s	remaining: 46.1s
196:	learn: 0.3369808	total: 15s	remaining: 46s
197:	learn: 0.3369047	total: 15.1s	remaining: 46s
198:	learn: 0.3367362	total: 15.2s	remaining: 45.9s
199:	learn: 0.3366659	total: 15.3s	remaining: 45.8s
200:	learn: 0.3365065	total: 15.4s	remaining: 45.8s
201:	learn: 0.3363162	total: 15.4s	remaining: 45.7s
202:	learn: 0.3361837	total: 15.5s	remaining: 45.6s
203:	learn: 0.3360250	total: 15.6s	remaining: 45.6s
204:	learn: 0.3359543	total: 15.7s	remaining: 45.5s
205:	learn: 0.3357576	total: 15.8s	remaining: 45.4s
206:	learn: 0.3356790	total: 15.8s	remaining: 45.4s
207:	learn: 0.3356401	total: 15.9s	remaining: 45.3s
208:	learn: 0.3353798	total: 16s	remaining: 45.3s
209:	learn: 0.3352509	total: 16.1s	remaining: 45.2s
210:	learn: 0.3351659	total: 16.1s	remaining: 45s
211:	learn: 0.3350062	total: 16.2s	remaining: 45s
212:	learn: 0.3349324	total: 16.3s	remaining: 44.9s
213:	learn: 0.3348571	total: 16.4s	remaining: 44.8s
214:	learn: 0.3346459	total: 16.4s	remaining: 44.7s
215:	learn: 0.3343728	total: 16.5s	remaining: 44.6s
216:	learn: 0.3342880	total: 16.6s	remaining: 44.5s
217:	learn: 0.3339811	total: 16.7s	remaining: 44.5s
218:	learn: 0.3339217	total: 16.7s	remaining: 44.4s
219:	learn: 0.3338762	total: 16.8s	remaining: 44.3s
220:	learn: 0.3338130	total: 16.9s	remaining: 44.3s
221:	learn: 0.3337064	total: 17s	remaining: 44.2s
222:	learn: 0.3335639	total: 17s	remaining: 44.1s
223:	learn: 0.3333994	total: 17.1s	remaining: 44s
224:	learn: 0.3332650	total: 17.2s	remaining: 43.9s
225:	learn: 0.3332151	total: 17.2s	remaining: 43.8s
226:	learn: 0.3330773	total: 17.3s	remaining: 43.8s
227:	learn: 0.3330394	total: 17.4s	remaining: 43.6s
228:	learn: 0.3329733	total: 17.5s	remaining: 43.6s
229:	learn: 0.3328308	total: 17.6s	remaining: 43.5s
230:	learn: 0.3327428	total: 17.6s	remaining: 43.4s
231:	learn: 0.3327126	total: 17.7s	remaining: 43.3s
232:	learn: 0.3326677	total: 17.8s	remaining: 43.2s
233:	learn: 0.3326247	total: 17.8s	remaining: 43.1s
234:	learn: 0.3325239	total: 17.9s	remaining: 43s
235:	learn: 0.3324014	total: 18s	remaining: 43s
236:	learn: 0.3322777	total: 18.1s	remaining: 42.9s
237:	learn: 0.3322191	total: 18.1s	remaining: 42.8s
238:	learn: 0.3321480	total: 18.2s	remaining: 42.7s
239:	learn: 0.3320315	total: 18.3s	remaining: 42.6s
240:	learn: 0.3319718	total: 18.3s	remaining: 42.5s
241:	learn: 0.3318103	total: 18.4s	remaining: 42.5s
242:	learn: 0.3317575	total: 18.6s	remaining: 42.6s
243:	learn: 0.3315862	total: 18.7s	remaining: 42.6s
244:	learn: 0.3314898	total: 18.9s	remaining: 42.7s
245:	learn: 0.3313326	total: 19s	remaining: 42.8s
246:	learn: 0.3311832	total: 19.1s	remaining: 42.8s
247:	learn: 0.3310403	total: 19.2s	remaining: 42.8s
248:	learn: 0.3309693	total: 19.4s	remaining: 42.8s
249:	learn: 0.3309124	total: 19.5s	remaining: 42.9s
250:	learn: 0.3307759	total: 19.6s	remaining: 42.8s
251:	learn: 0.3307032	total: 19.7s	remaining: 42.9s
252:	learn: 0.3305900	total: 19.8s	remaining: 42.9s
253:	learn: 0.3304595	total: 20s	remaining: 42.9s
254:	learn: 0.3303902	total: 20.1s	remaining: 42.9s
255:	learn: 0.3302794	total: 20.1s	remaining: 42.8s
256:	learn: 0.3300143	total: 20.2s	remaining: 42.7s
257:	learn: 0.3299469	total: 20.3s	remaining: 42.6s
258:	learn: 0.3299085	total: 20.4s	remaining: 42.5s
259:	learn: 0.3298757	total: 20.4s	remaining: 42.4s
260:	learn: 0.3298443	total: 20.5s	remaining: 42.3s
261:	learn: 0.3296652	total: 20.6s	remaining: 42.2s
262:	learn: 0.3295600	total: 20.6s	remaining: 42.2s
263:	learn: 0.3294987	total: 20.7s	remaining: 42.1s
264:	learn: 0.3294509	total: 20.8s	remaining: 42s
265:	learn: 0.3294071	total: 20.9s	remaining: 41.9s
266:	learn: 0.3292751	total: 20.9s	remaining: 41.8s
267:	learn: 0.3292371	total: 21s	remaining: 41.7s
268:	learn: 0.3289507	total: 21.1s	remaining: 41.6s
269:	learn: 0.3288868	total: 21.2s	remaining: 41.6s
270:	learn: 0.3287584	total: 21.2s	remaining: 41.5s
271:	learn: 0.3286680	total: 21.3s	remaining: 41.4s
272:	learn: 0.3286279	total: 21.4s	remaining: 41.3s
273:	learn: 0.3285523	total: 21.5s	remaining: 41.3s
274:	learn: 0.3284416	total: 21.6s	remaining: 41.2s
275:	learn: 0.3283535	total: 21.7s	remaining: 41.1s
276:	learn: 0.3282902	total: 21.7s	remaining: 41.1s
277:	learn: 0.3281945	total: 21.8s	remaining: 41s
278:	learn: 0.3280480	total: 21.9s	remaining: 40.9s
279:	learn: 0.3279238	total: 22s	remaining: 40.8s
280:	learn: 0.3278441	total: 22.1s	remaining: 40.8s
281:	learn: 0.3278090	total: 22.1s	remaining: 40.7s
282:	learn: 0.3277166	total: 22.2s	remaining: 40.6s
283:	learn: 0.3276754	total: 22.3s	remaining: 40.5s
284:	learn: 0.3276328	total: 22.4s	remaining: 40.5s
285:	learn: 0.3275966	total: 22.5s	remaining: 40.4s
286:	learn: 0.3274944	total: 22.6s	remaining: 40.3s
287:	learn: 0.3274465	total: 22.7s	remaining: 40.3s
288:	learn: 0.3274244	total: 22.7s	remaining: 40.2s
289:	learn: 0.3273594	total: 22.8s	remaining: 40.1s
290:	learn: 0.3273002	total: 22.9s	remaining: 40s
291:	learn: 0.3272401	total: 23s	remaining: 40s
292:	learn: 0.3271256	total: 23.1s	remaining: 39.9s
293:	learn: 0.3269953	total: 23.2s	remaining: 39.9s
294:	learn: 0.3269326	total: 23.2s	remaining: 39.8s
295:	learn: 0.3268179	total: 23.3s	remaining: 39.7s
296:	learn: 0.3267259	total: 23.4s	remaining: 39.7s
297:	learn: 0.3266707	total: 23.5s	remaining: 39.6s
298:	learn: 0.3266302	total: 23.6s	remaining: 39.5s
299:	learn: 0.3264694	total: 23.7s	remaining: 39.5s
300:	learn: 0.3263502	total: 23.8s	remaining: 39.4s
301:	learn: 0.3261753	total: 23.9s	remaining: 39.4s
302:	learn: 0.3260915	total: 24s	remaining: 39.3s
303:	learn: 0.3260277	total: 24s	remaining: 39.2s
304:	learn: 0.3259127	total: 24.1s	remaining: 39.2s
305:	learn: 0.3258460	total: 24.2s	remaining: 39.1s
306:	learn: 0.3257245	total: 24.3s	remaining: 39.1s
307:	learn: 0.3255928	total: 24.4s	remaining: 39s
308:	learn: 0.3255527	total: 24.5s	remaining: 38.9s
309:	learn: 0.3254911	total: 24.6s	remaining: 38.9s
310:	learn: 0.3254022	total: 24.7s	remaining: 38.8s
311:	learn: 0.3253348	total: 24.8s	remaining: 38.7s
312:	learn: 0.3252823	total: 24.9s	remaining: 38.7s
313:	learn: 0.3251755	total: 24.9s	remaining: 38.6s
314:	learn: 0.3250994	total: 25s	remaining: 38.5s
315:	learn: 0.3249838	total: 25.1s	remaining: 38.5s
316:	learn: 0.3249294	total: 25.2s	remaining: 38.4s
317:	learn: 0.3249018	total: 25.3s	remaining: 38.3s
318:	learn: 0.3248668	total: 25.4s	remaining: 38.3s
319:	learn: 0.3247457	total: 25.5s	remaining: 38.2s
320:	learn: 0.3246858	total: 25.5s	remaining: 38.1s
321:	learn: 0.3245660	total: 25.6s	remaining: 38s
322:	learn: 0.3244729	total: 25.7s	remaining: 38s
323:	learn: 0.3243901	total: 25.8s	remaining: 37.9s
324:	learn: 0.3242760	total: 25.9s	remaining: 37.8s
325:	learn: 0.3241819	total: 26s	remaining: 37.8s
326:	learn: 0.3240765	total: 26.1s	remaining: 37.7s
327:	learn: 0.3239918	total: 26.2s	remaining: 37.7s
328:	learn: 0.3239075	total: 26.3s	remaining: 37.6s
329:	learn: 0.3237293	total: 26.4s	remaining: 37.6s
330:	learn: 0.3236599	total: 26.5s	remaining: 37.5s
331:	learn: 0.3236215	total: 26.6s	remaining: 37.5s
332:	learn: 0.3235046	total: 26.6s	remaining: 37.4s
333:	learn: 0.3234848	total: 26.7s	remaining: 37.3s
334:	learn: 0.3234527	total: 26.8s	remaining: 37.3s
335:	learn: 0.3233147	total: 26.9s	remaining: 37.2s
336:	learn: 0.3232550	total: 27s	remaining: 37.1s
337:	learn: 0.3231090	total: 27.1s	remaining: 37s
338:	learn: 0.3230013	total: 27.2s	remaining: 37s
339:	learn: 0.3229035	total: 27.3s	remaining: 36.9s
340:	learn: 0.3228116	total: 27.4s	remaining: 36.8s
341:	learn: 0.3227307	total: 27.5s	remaining: 36.8s
342:	learn: 0.3226870	total: 27.6s	remaining: 36.7s
343:	learn: 0.3226291	total: 27.7s	remaining: 36.7s
344:	learn: 0.3224711	total: 27.7s	remaining: 36.6s
345:	learn: 0.3223732	total: 27.8s	remaining: 36.5s
346:	learn: 0.3223477	total: 27.9s	remaining: 36.4s
347:	learn: 0.3223168	total: 28s	remaining: 36.4s
348:	learn: 0.3222116	total: 28.1s	remaining: 36.3s
349:	learn: 0.3221546	total: 28.2s	remaining: 36.2s
350:	learn: 0.3220400	total: 28.2s	remaining: 36.1s
351:	learn: 0.3219774	total: 28.4s	remaining: 36.1s
352:	learn: 0.3218993	total: 28.4s	remaining: 36s
353:	learn: 0.3216950	total: 28.5s	remaining: 35.9s
354:	learn: 0.3216405	total: 28.6s	remaining: 35.8s
355:	learn: 0.3214993	total: 28.7s	remaining: 35.8s
356:	learn: 0.3213138	total: 28.8s	remaining: 35.7s
357:	learn: 0.3211944	total: 28.8s	remaining: 35.6s
358:	learn: 0.3211276	total: 28.9s	remaining: 35.5s
359:	learn: 0.3210301	total: 29s	remaining: 35.5s
360:	learn: 0.3209771	total: 29.1s	remaining: 35.4s
361:	learn: 0.3209356	total: 29.2s	remaining: 35.3s
362:	learn: 0.3209052	total: 29.3s	remaining: 35.2s
363:	learn: 0.3208219	total: 29.4s	remaining: 35.2s
364:	learn: 0.3207672	total: 29.5s	remaining: 35.1s
365:	learn: 0.3206703	total: 29.5s	remaining: 35s
366:	learn: 0.3204811	total: 29.6s	remaining: 34.9s
367:	learn: 0.3204108	total: 29.7s	remaining: 34.8s
368:	learn: 0.3203747	total: 29.8s	remaining: 34.8s
369:	learn: 0.3202631	total: 29.8s	remaining: 34.7s
370:	learn: 0.3201760	total: 29.9s	remaining: 34.6s
371:	learn: 0.3200195	total: 30s	remaining: 34.5s
372:	learn: 0.3198989	total: 30.1s	remaining: 34.5s
373:	learn: 0.3198845	total: 30.3s	remaining: 34.5s
374:	learn: 0.3198607	total: 30.5s	remaining: 34.6s
375:	learn: 0.3197971	total: 30.6s	remaining: 34.6s
376:	learn: 0.3197461	total: 30.8s	remaining: 34.6s
377:	learn: 0.3196606	total: 30.9s	remaining: 34.5s
378:	learn: 0.3195932	total: 31.1s	remaining: 34.5s
379:	learn: 0.3195804	total: 31.2s	remaining: 34.5s
380:	learn: 0.3195185	total: 31.4s	remaining: 34.5s
381:	learn: 0.3194506	total: 31.5s	remaining: 34.5s
382:	learn: 0.3193876	total: 31.7s	remaining: 34.5s
383:	learn: 0.3193214	total: 31.8s	remaining: 34.4s
384:	learn: 0.3191655	total: 31.8s	remaining: 34.3s
385:	learn: 0.3190994	total: 31.9s	remaining: 34.2s
386:	learn: 0.3189786	total: 32s	remaining: 34.1s
387:	learn: 0.3189296	total: 32.1s	remaining: 34s
388:	learn: 0.3186599	total: 32.1s	remaining: 34s

/content/mlutils.py:50: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, pd.DataFrame([result_row])], ignore_index=True)

{'timestamp': '2026-06-15T18:35:35.296278',
 'method': 'catboost',
 'params': '{"iterations": 800, "depth": 5, "learning_rate": 0.1398336717868352, "l2_leaf_reg": 0.2265442520413868, "early_stopping_rounds": 100, "cat_features": ["hotel", "arrival_date_month", "meal", "country", "market_segment", "distribution_channel", "reserved_room_type", "assigned_room_type", "deposit_type", "customer_type"]}',
 'score': 0.7067760150578113,
 'duration_sec': 65.63863396644592}

## TabNet

In [ ]:
!pip install pytorch-tabnet

Collecting pytorch-tabnet
  Downloading pytorch_tabnet-4.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (2.0.2)
Requirement already satisfied: scikit_learn>0.21 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (1.6.1)
Requirement already satisfied: scipy>1.4 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (1.16.3)
Requirement already satisfied: torch>=1.3 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (2.11.0+cu128)
Requirement already satisfied: tqdm>=4.36 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (3.29.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.3->pytorch-tabnet) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.3->pytorch-tabnet) (1.5.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.3->pytorch-tabnet) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.3->pytorch-tabnet) (3.0.3)
Downloading pytorch_tabnet-4.1.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.5/44.5 kB 2.4 MB/s eta 0:00:00
Installing collected packages: pytorch-tabnet
Successfully installed pytorch-tabnet-4.1.0

In [ ]:
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
import torch

In [ ]:
X = df_model[[c for c in df_model.columns if c not in ['is_canceled','country_full']]].copy()
y = df_model.is_canceled.copy()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=8)

In [ ]:
num_features = [
    'lead_time', 'arrival_date_year', 'arrival_date_week_number',
    'arrival_date_day_of_month', 'stays_in_weekend_nights',
    'stays_in_week_nights', 'adults', 'children', 'babies',
    'is_repeated_guest', 'previous_cancellations',
    'previous_bookings_not_canceled', 'booking_changes',
    'days_in_waiting_list', 'required_car_parking_spaces',
    'total_of_special_requests'
]

cat_features = [
    'hotel', 'arrival_date_month', 'meal', 'country',
    'market_segment', 'distribution_channel', 'reserved_room_type',
    'assigned_room_type', 'deposit_type', 'customer_type'
]

In [ ]:
categories_list = [list(X_train[col].astype(str).unique()) for col in cat_features]

In [ ]:
cat_dims = [int(X_train[col].nunique()) for col in cat_features]
cat_idxs = list(range(len(cat_features)))

n_d (Dimension of prediction layer): Размерность слоя предсказаний. Чем больше датасет и чем больше в нем сложных взаимосвязей, тем выше должно быть это число (обычно от 8 до 64).

n_a (Dimension of attention layer): Размерность слоя внимания.

Золотое правило TabNet: Практически всегда выставляют n_d = n_a. Чтобы не тратить время Optuna на перебор бессмысленных комбинаций, лучше заставить её подбирать одно число для обоих параметров.

n_steps: Количество шагов архитектуры (можно метафорически сравнить с количеством последовательных деревьев в бустинге). Обычно подбирается в диапазоне от 3 до 10. Больше 10 часто ведет к дикому переобучению и долгому обучению.

gamma: Коэффициент повторного использования признаков на разных шагах внимания. Если gamma = 1.0, признаки выбираются независимо на каждом шаге. Диапазон: от 1.0 до 2.0.

n_independent и n_shared: Количество независимых и разделяемых (shared) блоков GLU (Gated Linear Units). Обычно берут от 1 до 5.

Регуляризация и обучение
lambda_sparse: Пожалуй, самый критичный параметр. Он отвечает за "разреженность" (sparsity) внимания - заставлять ли модель выбирать только самые важные признаки или размазывать внимание по всем. Варьируется логарифмически от 1e-6 до 1e-1.

mask_type: Тип функции активации для выбора признаков: 'sparsemax' (жестко зануляет неважные признаки) или 'entmax' (более мягкий вариант).

virtual_batch_size: Размер батча для Ghost Batch Normalization. TabNet очень чувствителен к нормализации. Обычно основной batch_size делают большим (например, 1024 или 2048), а virtual_batch_size — поменьше (32, 64, 128). Он обязательно должен быть делителем основного батча!

In [ ]:
def objective_tabnet(trial):
    n_da = trial.suggest_int('n_da', 8, 64, step=8)
    batch_size = trial.suggest_categorical('batch_size', [512, 1024, 2048])
    virtual_batch_size = trial.suggest_categorical('virtual_batch_size', [32, 64, 128])

    if virtual_batch_size > batch_size:
        virtual_batch_size = batch_size

    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=8)
    scores = []

    for train_idx, val_idx in cv.split(X_train, y_train):
        X_tr, X_va = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr = y_train.iloc[train_idx] if hasattr(y_train, 'iloc') else y_train[train_idx]
        y_va = y_train.iloc[val_idx] if hasattr(y_train, 'iloc') else y_train[val_idx]

        preprocessor = ColumnTransformer(
            transformers=[
                ('cat', OrdinalEncoder(
                    categories=categories_list,
                    handle_unknown='use_encoded_value',
                    unknown_value=-1
                ), cat_features)
            ],
            remainder='passthrough'
        )

        classifier = TabNetClassifier(
            cat_idxs=cat_idxs,
            cat_dims=cat_dims,
            n_d=n_da,
            n_a=n_da,
            n_steps=trial.suggest_int('n_steps', 3, 8),
            gamma=trial.suggest_float('gamma', 1.0, 1.8),
            lambda_sparse=trial.suggest_float('lambda_sparse', 1e-5, 1e-1, log=True),
            n_independent=trial.suggest_int('n_independent', 1, 4),
            n_shared=trial.suggest_int('n_shared', 1, 4),
            mask_type=trial.suggest_categorical('mask_type', ['sparsemax', 'entmax']),
            optimizer_fn=torch.optim.Adam,
            optimizer_params=dict(lr=trial.suggest_float('lr', 1e-3, 5e-2, log=True)),
            scheduler_fn=torch.optim.lr_scheduler.StepLR,
            scheduler_params={"step_size": 10, "gamma": 0.9},
            verbose=0,
            device_name='cuda' if torch.cuda.is_available() else 'cpu'
        )

        tabnet_pipeline = Pipeline([
            ('preprocessor', preprocessor),
            ('classifier', classifier)
        ])

        preprocessor.fit(X_tr)
        X_va_transformed = preprocessor.transform(X_va)

        y_tr_arr = np.asarray(y_tr)
        y_va_arr = np.asarray(y_va)

        tabnet_pipeline.fit(
            X_tr, y_tr_arr,
            classifier__eval_set=[(X_va_transformed, y_va_arr)],
            classifier__eval_metric=['balanced_accuracy'],
            classifier__max_epochs=50,
            classifier__patience=10,
            classifier__batch_size=batch_size,
            classifier__virtual_batch_size=virtual_batch_size
        )

        preds = tabnet_pipeline.predict(X_va)
        scores.append(f1_score(y_va_arr, preds))

    return np.mean(scores)

In [ ]:
study_tabnet = optuna.create_study(direction='maximize')
study_tabnet.optimize(objective_tabnet, n_trials=20, show_progress_bar=True)

[I 2026-06-15 20:33:58,509] A new study created in memory with name: no-name-975a9ff1-0618-4269-971c-e6b2f43cd17a

  0%|          | 0/20 [00:00<?, ?it/s]

Early stopping occurred at epoch 11 with best_epoch = 1 and best_val_0_balanced_accuracy = 0.52874

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Stop training because you reached max_epochs = 50 with best_epoch = 40 and best_val_0_balanced_accuracy = 0.72582

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_balanced_accuracy = 0.54207

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 20:41:01,327] Trial 0 finished with value: 0.48015247919217874 and parameters: {'n_da': 56, 'batch_size': 2048, 'virtual_batch_size': 128, 'n_steps': 8, 'gamma': 1.2452958959383584, 'lambda_sparse': 0.005438866606637981, 'n_independent': 3, 'n_shared': 3, 'mask_type': 'entmax', 'lr': 0.0026362172105946434}. Best is trial 0 with value: 0.48015247919217874.

Early stopping occurred at epoch 16 with best_epoch = 6 and best_val_0_balanced_accuracy = 0.57468

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 16 with best_epoch = 6 and best_val_0_balanced_accuracy = 0.55768

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 34 with best_epoch = 24 and best_val_0_balanced_accuracy = 0.61777

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 21:11:30,746] Trial 1 finished with value: 0.388663050992029 and parameters: {'n_da': 40, 'batch_size': 512, 'virtual_batch_size': 32, 'n_steps': 8, 'gamma': 1.7895031389729088, 'lambda_sparse': 0.02078052835172046, 'n_independent': 4, 'n_shared': 4, 'mask_type': 'sparsemax', 'lr': 0.003893996327301261}. Best is trial 0 with value: 0.48015247919217874.

Early stopping occurred at epoch 48 with best_epoch = 38 and best_val_0_balanced_accuracy = 0.73811

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Stop training because you reached max_epochs = 50 with best_epoch = 47 and best_val_0_balanced_accuracy = 0.73061

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 28 with best_epoch = 18 and best_val_0_balanced_accuracy = 0.67701

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 21:23:23,737] Trial 2 finished with value: 0.5896922837575702 and parameters: {'n_da': 24, 'batch_size': 1024, 'virtual_batch_size': 128, 'n_steps': 7, 'gamma': 1.405337945744821, 'lambda_sparse': 2.4436425926724718e-05, 'n_independent': 1, 'n_shared': 4, 'mask_type': 'entmax', 'lr': 0.004076573010615059}. Best is trial 2 with value: 0.5896922837575702.
Stop training because you reached max_epochs = 50 with best_epoch = 47 and best_val_0_balanced_accuracy = 0.62762

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Stop training because you reached max_epochs = 50 with best_epoch = 45 and best_val_0_balanced_accuracy = 0.62475

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 42 with best_epoch = 32 and best_val_0_balanced_accuracy = 0.67013

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 21:29:58,604] Trial 3 finished with value: 0.45729137862081365 and parameters: {'n_da': 24, 'batch_size': 2048, 'virtual_batch_size': 128, 'n_steps': 5, 'gamma': 1.610781961354832, 'lambda_sparse': 0.0065536428952974275, 'n_independent': 2, 'n_shared': 2, 'mask_type': 'sparsemax', 'lr': 0.001947478525957296}. Best is trial 2 with value: 0.5896922837575702.

Early stopping occurred at epoch 19 with best_epoch = 9 and best_val_0_balanced_accuracy = 0.56566

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Stop training because you reached max_epochs = 50 with best_epoch = 46 and best_val_0_balanced_accuracy = 0.68748

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Stop training because you reached max_epochs = 50 with best_epoch = 49 and best_val_0_balanced_accuracy = 0.67674

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 21:46:58,713] Trial 4 finished with value: 0.48749967390144083 and parameters: {'n_da': 32, 'batch_size': 2048, 'virtual_batch_size': 32, 'n_steps': 4, 'gamma': 1.449310150386549, 'lambda_sparse': 0.0007054446770544621, 'n_independent': 4, 'n_shared': 2, 'mask_type': 'entmax', 'lr': 0.0010762786354759368}. Best is trial 2 with value: 0.5896922837575702.
Stop training because you reached max_epochs = 50 with best_epoch = 41 and best_val_0_balanced_accuracy = 0.7693

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 24 with best_epoch = 14 and best_val_0_balanced_accuracy = 0.76058

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 37 with best_epoch = 27 and best_val_0_balanced_accuracy = 0.76449

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 21:58:08,718] Trial 5 finished with value: 0.658299007146184 and parameters: {'n_da': 48, 'batch_size': 512, 'virtual_batch_size': 128, 'n_steps': 7, 'gamma': 1.0984651701755204, 'lambda_sparse': 0.056504430571300085, 'n_independent': 2, 'n_shared': 1, 'mask_type': 'sparsemax', 'lr': 0.012465577331328147}. Best is trial 5 with value: 0.658299007146184.

Early stopping occurred at epoch 30 with best_epoch = 20 and best_val_0_balanced_accuracy = 0.74167

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Stop training because you reached max_epochs = 50 with best_epoch = 49 and best_val_0_balanced_accuracy = 0.74792

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 28 with best_epoch = 18 and best_val_0_balanced_accuracy = 0.72304

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 22:19:52,910] Trial 6 finished with value: 0.6245968202994862 and parameters: {'n_da': 16, 'batch_size': 512, 'virtual_batch_size': 32, 'n_steps': 6, 'gamma': 1.3845162775968927, 'lambda_sparse': 0.008131841814662612, 'n_independent': 1, 'n_shared': 3, 'mask_type': 'entmax', 'lr': 0.01107458926312298}. Best is trial 5 with value: 0.658299007146184.

Early stopping occurred at epoch 46 with best_epoch = 36 and best_val_0_balanced_accuracy = 0.77766

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 18 with best_epoch = 8 and best_val_0_balanced_accuracy = 0.72074

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 33 with best_epoch = 23 and best_val_0_balanced_accuracy = 0.73646

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 22:42:58,067] Trial 7 finished with value: 0.6335263342024641 and parameters: {'n_da': 16, 'batch_size': 512, 'virtual_batch_size': 32, 'n_steps': 6, 'gamma': 1.6834221160104001, 'lambda_sparse': 4.4320277911827404e-05, 'n_independent': 1, 'n_shared': 4, 'mask_type': 'sparsemax', 'lr': 0.03448852113560604}. Best is trial 5 with value: 0.658299007146184.

Early stopping occurred at epoch 32 with best_epoch = 22 and best_val_0_balanced_accuracy = 0.76782

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 39 with best_epoch = 29 and best_val_0_balanced_accuracy = 0.73919

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 38 with best_epoch = 28 and best_val_0_balanced_accuracy = 0.73035

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 23:03:48,674] Trial 8 finished with value: 0.6235661483855991 and parameters: {'n_da': 32, 'batch_size': 1024, 'virtual_batch_size': 32, 'n_steps': 7, 'gamma': 1.3956952206627466, 'lambda_sparse': 5.380958849496902e-05, 'n_independent': 1, 'n_shared': 3, 'mask_type': 'entmax', 'lr': 0.03460044251746503}. Best is trial 5 with value: 0.658299007146184.

Early stopping occurred at epoch 29 with best_epoch = 19 and best_val_0_balanced_accuracy = 0.78487

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 32 with best_epoch = 22 and best_val_0_balanced_accuracy = 0.79509

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 41 with best_epoch = 31 and best_val_0_balanced_accuracy = 0.79059

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 23:12:00,528] Trial 9 finished with value: 0.6951575973149732 and parameters: {'n_da': 56, 'batch_size': 512, 'virtual_batch_size': 64, 'n_steps': 3, 'gamma': 1.7197520573393925, 'lambda_sparse': 0.0010362422866200787, 'n_independent': 1, 'n_shared': 3, 'mask_type': 'entmax', 'lr': 0.006042998158754487}. Best is trial 9 with value: 0.6951575973149732.

Early stopping occurred at epoch 33 with best_epoch = 23 and best_val_0_balanced_accuracy = 0.7966

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 29 with best_epoch = 19 and best_val_0_balanced_accuracy = 0.79295

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 21 with best_epoch = 11 and best_val_0_balanced_accuracy = 0.7812

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 23:18:47,135] Trial 10 finished with value: 0.6964153363868735 and parameters: {'n_da': 64, 'batch_size': 512, 'virtual_batch_size': 64, 'n_steps': 3, 'gamma': 1.006735572418443, 'lambda_sparse': 0.0004738308181254077, 'n_independent': 3, 'n_shared': 1, 'mask_type': 'entmax', 'lr': 0.009773356885931204}. Best is trial 10 with value: 0.6964153363868735.

Early stopping occurred at epoch 26 with best_epoch = 16 and best_val_0_balanced_accuracy = 0.79539

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 37 with best_epoch = 27 and best_val_0_balanced_accuracy = 0.78867

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 32 with best_epoch = 22 and best_val_0_balanced_accuracy = 0.79058

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 23:26:27,285] Trial 11 finished with value: 0.6975213814697221 and parameters: {'n_da': 64, 'batch_size': 512, 'virtual_batch_size': 64, 'n_steps': 3, 'gamma': 1.05384973384255, 'lambda_sparse': 0.000489340595685369, 'n_independent': 3, 'n_shared': 1, 'mask_type': 'entmax', 'lr': 0.010138165582984094}. Best is trial 11 with value: 0.6975213814697221.

Early stopping occurred at epoch 33 with best_epoch = 23 and best_val_0_balanced_accuracy = 0.79419

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 29 with best_epoch = 19 and best_val_0_balanced_accuracy = 0.78925

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 35 with best_epoch = 25 and best_val_0_balanced_accuracy = 0.79437

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 23:34:21,443] Trial 12 finished with value: 0.699837705024471 and parameters: {'n_da': 64, 'batch_size': 512, 'virtual_batch_size': 64, 'n_steps': 3, 'gamma': 1.0017790891171632, 'lambda_sparse': 0.0002438993046147159, 'n_independent': 3, 'n_shared': 1, 'mask_type': 'entmax', 'lr': 0.013560933794746042}. Best is trial 12 with value: 0.699837705024471.

Early stopping occurred at epoch 44 with best_epoch = 34 and best_val_0_balanced_accuracy = 0.79943

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 43 with best_epoch = 33 and best_val_0_balanced_accuracy = 0.78917

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 19 with best_epoch = 9 and best_val_0_balanced_accuracy = 0.79103

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 23:44:50,712] Trial 13 finished with value: 0.6954102490411834 and parameters: {'n_da': 64, 'batch_size': 512, 'virtual_batch_size': 64, 'n_steps': 4, 'gamma': 1.1402601499366438, 'lambda_sparse': 0.0001866284181118285, 'n_independent': 3, 'n_shared': 1, 'mask_type': 'entmax', 'lr': 0.019531109224762148}. Best is trial 12 with value: 0.699837705024471.

Early stopping occurred at epoch 29 with best_epoch = 19 and best_val_0_balanced_accuracy = 0.79259

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 41 with best_epoch = 31 and best_val_0_balanced_accuracy = 0.79289

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 33 with best_epoch = 23 and best_val_0_balanced_accuracy = 0.79545

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-15 23:54:28,852] Trial 14 finished with value: 0.6987827986812071 and parameters: {'n_da': 64, 'batch_size': 512, 'virtual_batch_size': 64, 'n_steps': 3, 'gamma': 1.0072562083502223, 'lambda_sparse': 0.0001823206040240092, 'n_independent': 3, 'n_shared': 2, 'mask_type': 'entmax', 'lr': 0.017056487832493708}. Best is trial 12 with value: 0.699837705024471.

Early stopping occurred at epoch 46 with best_epoch = 36 and best_val_0_balanced_accuracy = 0.79635

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 12 with best_epoch = 2 and best_val_0_balanced_accuracy = 0.6116

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 42 with best_epoch = 32 and best_val_0_balanced_accuracy = 0.79522

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-16 00:02:04,114] Trial 15 finished with value: 0.6330042334618867 and parameters: {'n_da': 48, 'batch_size': 1024, 'virtual_batch_size': 64, 'n_steps': 4, 'gamma': 1.2359625046523022, 'lambda_sparse': 0.00012539454857096516, 'n_independent': 2, 'n_shared': 2, 'mask_type': 'entmax', 'lr': 0.02165932822726247}. Best is trial 12 with value: 0.699837705024471.

Early stopping occurred at epoch 41 with best_epoch = 31 and best_val_0_balanced_accuracy = 0.79512

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 19 with best_epoch = 9 and best_val_0_balanced_accuracy = 0.78814

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 38 with best_epoch = 28 and best_val_0_balanced_accuracy = 0.8049

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-16 00:12:34,524] Trial 16 finished with value: 0.7009890116949098 and parameters: {'n_da': 56, 'batch_size': 512, 'virtual_batch_size': 64, 'n_steps': 3, 'gamma': 1.2126647444379608, 'lambda_sparse': 1.0088907457764974e-05, 'n_independent': 4, 'n_shared': 2, 'mask_type': 'entmax', 'lr': 0.04973945735856026}. Best is trial 16 with value: 0.7009890116949098.

Early stopping occurred at epoch 26 with best_epoch = 16 and best_val_0_balanced_accuracy = 0.7908

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 40 with best_epoch = 30 and best_val_0_balanced_accuracy = 0.79329

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 25 with best_epoch = 15 and best_val_0_balanced_accuracy = 0.79686

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-16 00:25:32,904] Trial 17 finished with value: 0.6978794257797531 and parameters: {'n_da': 48, 'batch_size': 512, 'virtual_batch_size': 64, 'n_steps': 4, 'gamma': 1.2151888138100924, 'lambda_sparse': 1.040000592467489e-05, 'n_independent': 4, 'n_shared': 2, 'mask_type': 'entmax', 'lr': 0.03971560033017644}. Best is trial 16 with value: 0.7009890116949098.

Early stopping occurred at epoch 35 with best_epoch = 25 and best_val_0_balanced_accuracy = 0.76351

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 26 with best_epoch = 16 and best_val_0_balanced_accuracy = 0.69505

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Stop training because you reached max_epochs = 50 with best_epoch = 45 and best_val_0_balanced_accuracy = 0.75335

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-16 00:35:24,723] Trial 18 finished with value: 0.6144806070607469 and parameters: {'n_da': 56, 'batch_size': 2048, 'virtual_batch_size': 64, 'n_steps': 5, 'gamma': 1.1540533583531687, 'lambda_sparse': 1.0365664401515646e-05, 'n_independent': 4, 'n_shared': 1, 'mask_type': 'sparsemax', 'lr': 0.04853645362588668}. Best is trial 16 with value: 0.7009890116949098.

Early stopping occurred at epoch 12 with best_epoch = 2 and best_val_0_balanced_accuracy = 0.66379

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 35 with best_epoch = 25 and best_val_0_balanced_accuracy = 0.78867

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

Early stopping occurred at epoch 28 with best_epoch = 18 and best_val_0_balanced_accuracy = 0.78843

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

[I 2026-06-16 00:41:46,737] Trial 19 finished with value: 0.6366677800293881 and parameters: {'n_da': 56, 'batch_size': 1024, 'virtual_batch_size': 64, 'n_steps': 3, 'gamma': 1.3067894659429709, 'lambda_sparse': 0.003382670732225801, 'n_independent': 4, 'n_shared': 2, 'mask_type': 'entmax', 'lr': 0.0256425792146109}. Best is trial 16 with value: 0.7009890116949098.

In [ ]:
study_tabnet.best_params

{'n_da': 56,
 'batch_size': 512,
 'virtual_batch_size': 64,
 'n_steps': 3,
 'gamma': 1.2126647444379608,
 'lambda_sparse': 1.0088907457764974e-05,
 'n_independent': 4,
 'n_shared': 2,
 'mask_type': 'entmax',
 'lr': 0.04973945735856026}

In [14]:
!pip install torch

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [15]:
!pip install pytorch-tabnet

Collecting pytorch-tabnet
  Downloading pytorch_tabnet-4.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (2.0.2)
Requirement already satisfied: scikit_learn>0.21 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (1.6.1)
Requirement already satisfied: scipy>1.4 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (1.16.3)
Requirement already satisfied: torch>=1.3 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (2.11.0+cpu)
Requirement already satisfied: tqdm>=4.36 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (3.29.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.3->pytorch-tabnet) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.3->pytorch-tabnet) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.3->pytorch-tabnet) (3.0.3)
Downloading pytorch_tabnet-4.1.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.5/44.5 kB 1.7 MB/s eta 0:00:00
Installing collected packages: pytorch-tabnet
Successfully installed pytorch-tabnet-4.1.0

In [43]:
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder, FunctionTransformer
import torch

In [44]:
num_features = [
    'lead_time', 'arrival_date_year', 'arrival_date_week_number',
    'arrival_date_day_of_month', 'stays_in_weekend_nights',
    'stays_in_week_nights', 'adults', 'children', 'babies',
    'is_repeated_guest', 'previous_cancellations',
    'previous_bookings_not_canceled', 'booking_changes',
    'days_in_waiting_list', 'required_car_parking_spaces',
    'total_of_special_requests'
]

cat_features = [
    'hotel', 'arrival_date_month', 'meal', 'country',
    'market_segment', 'distribution_channel', 'reserved_room_type',
    'assigned_room_type', 'deposit_type', 'customer_type'
]

In [45]:
categories_list = [list(X_train[col].astype(str).unique()) for col in cat_features]

In [46]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', make_pipeline(
            OrdinalEncoder(
                handle_unknown='use_encoded_value',
                unknown_value=-1,
                encoded_missing_value=-1
            ),
            FunctionTransformer(lambda x: x + 1)
        ), cat_features)
    ],
    remainder='passthrough'
)

In [47]:
import scipy.sparse as sp

In [48]:
X_train_trans = preprocessor.fit_transform(X_train)

if sp.issparse(X_train_trans):
    X_train_trans_np = X_train_trans.toarray()
else:
    X_train_trans_np = np.asarray(X_train_trans)

In [49]:
X_train_trans = preprocessor.fit_transform(X_train)
X_train_trans_np = np.asarray(X_train_trans)

cat_idxs = list(range(len(cat_features)))
cat_dims = [int(X_train_trans_np[:, i].max()) + 1 for i in cat_idxs]

In [50]:
tabnet_pipeline = Pipeline([
            ('preprocessor', preprocessor),
            ('classifier', TabNetClassifier(
                cat_idxs=cat_idxs,
                cat_dims=cat_dims,
                n_d=56,
                n_a=56,
                n_steps=3,
                gamma=1.2126647444379608,
                lambda_sparse=1.0088907457764974e-05,
                n_independent=4,
                n_shared=2,
                mask_type='entmax',
                optimizer_fn=torch.optim.Adam,
                optimizer_params=dict(lr=0.04973945735856026),
                scheduler_fn=torch.optim.lr_scheduler.StepLR,
                scheduler_params={"step_size": 10, "gamma": 0.9},
                verbose=0,
                device_name = 'cpu'
        ))
        ])

In [51]:
tabnet_pipeline.fit(
    X_train, y_train.values,
    classifier__max_epochs=100,
    classifier__batch_size=512,
    classifier__virtual_batch_size=64
)

/usr/local/lib/python3.12/dist-packages/pytorch_tabnet/abstract_model.py:687: UserWarning: No early stopping will be performed, last training weights will be used.
  warnings.warn(wrn_msg)
/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  Pipeline(steps=[('ordinalencoder',
                                                                   OrdinalEncoder(encoded_missing_value=-1,
                                                                                  handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1)),
                                                                  ('functiontransformer',
                                                                   FunctionTransformer(func=<function <lambda> at 0x7907dddeb6a0>))]),
                                                  ['hotel',
                                                   'arrival_date_month', 'meal',
                                                   'co...
                                  lambda_sparse=1.0088907457764974e-05,
                                  seed=0,
                                  clip_value=1,
                                  verbose=0,
                                  optimizer_fn=<class 'torch.optim.adam.Adam'>,
                                  optimizer_params={'lr': 0.04973945735856026},
                                  scheduler_fn=<class 'torch.optim.lr_scheduler.StepLR'>,
                                  scheduler_params={'gamma': 0.9,
                                                    'step_size': 10},
                                  mask_type='entmax',
                                  input_dim=28,
                                  output_dim=2,
                                  device_name='cpu',
                                  n_shared_decoder=1,
                                  n_indep_decoder=1,
                                  grouped_features=[]))])

In [52]:
y_pred = tabnet_pipeline.predict(X_test)

In [53]:
f1_score(y_test, y_pred)

0.6686916413544831

# Построение моделей машинного обучения до FE. Регрессия.

In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 6.7 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.3 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [86]:
import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split, KFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.svm import LinearSVC, LinearSVR
from sklearn.metrics import f1_score
import catboost as cb
from catboost import CatBoostClassifier
import optuna
import mlutils as mu

In [55]:
df = pd.read_parquet('main_df_edited_no_dup.parquet')

In [56]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,country_full,arrival_date_month_num
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01,Portugal,6
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01,Portugal,6
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02,United Kingdom,6
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02,United Kingdom,6
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,0,Transient,98.00,0,1,Check-Out,2015-07-03,United Kingdom,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118893,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,0,Transient,96.14,0,0,Check-Out,2017-09-06,Belgium,7
118894,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,0,Transient,225.43,0,2,Check-Out,2017-09-07,France,7
118895,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,0,Transient,157.71,0,4,Check-Out,2017-09-07,Germany,7
118896,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,0,Transient,104.40,0,0,Check-Out,2017-09-07,United Kingdom,7
118897,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,0,Transient,151.20,0,2,Check-Out,2017-09-07,Germany,7

In [57]:
# Линейные модели logistic_regression / linear, Даниэль
#  svm Игорь
#  boosting Игорь
#  random trees Даниэль
#  нейронка Игорь
#  изотоническая регрессия Даниэль
#  ранжирование попробовать? Игорь

#  Для каждой затюнить гиперпараметры через GridSearchCV или optuna
#  Результаты по проведенным экспериментам собрать в pandas датасет и отправить
#  Сделать выводы по performance моделю, посмотреть на важность признаков через shap или feature_importances


#  Графики с дубликатами и без сравнить

In [58]:
df_model = df[[c for c in df.columns if c not in ['reservation_status', 'reservation_status_date', 'country_full']]]

In [59]:
df_model

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,arrival_date_month_num
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,C,C,3,No Deposit,0,Transient,0.00,0,0,6
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,C,C,4,No Deposit,0,Transient,0.00,0,0,6
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,A,C,0,No Deposit,0,Transient,75.00,0,0,6
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,A,A,0,No Deposit,0,Transient,75.00,0,0,6
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,A,A,0,No Deposit,0,Transient,98.00,0,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118893,City Hotel,0,23,2017,August,35,30,2,5,2,...,A,A,0,No Deposit,0,Transient,96.14,0,0,7
118894,City Hotel,0,102,2017,August,35,31,2,5,3,...,E,E,0,No Deposit,0,Transient,225.43,0,2,7
118895,City Hotel,0,34,2017,August,35,31,2,5,2,...,D,D,0,No Deposit,0,Transient,157.71,0,4,7
118896,City Hotel,0,109,2017,August,35,31,2,5,2,...,A,A,0,No Deposit,0,Transient,104.40,0,0,7
118897,City Hotel,0,205,2017,August,35,29,2,7,2,...,A,A,0,No Deposit,0,Transient,151.20,0,2,7

In [60]:
X = df_model[[c for c in df_model.columns if c != 'adr']].copy()
y = df_model.adr.copy()

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8)

## SVM

In [92]:
num_features = [
    'lead_time', 'arrival_date_year', 'arrival_date_week_number',
    'arrival_date_day_of_month', 'stays_in_weekend_nights',
    'stays_in_week_nights', 'adults', 'children', 'babies',
    'is_repeated_guest', 'previous_cancellations',
    'previous_bookings_not_canceled', 'booking_changes',
    'days_in_waiting_list', 'required_car_parking_spaces',
    'total_of_special_requests'
]

cat_features = [
    'hotel', 'arrival_date_month', 'meal', 'country',
    'market_segment', 'distribution_channel', 'reserved_room_type',
    'assigned_room_type', 'deposit_type', 'customer_type'
]

In [93]:
preprocessor = ColumnTransformer(
    transformers=[
        ('scaler', StandardScaler(), num_features),
        ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), cat_features)
    ]
)

In [94]:
svm_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearSVR( random_state=8)),
])

In [97]:
def objective(trial):

    max_iter_param = trial.suggest_int('regressor__max_iter', 1000, 10000, step=1000)
    tol_param = trial.suggest_float('regressor__tol', 1e-5, 1e-2, log=True)
    c_param = trial.suggest_float('regressor__C', 1e-4, 1e2, log=True)

    svm_pipeline.set_params(
        regressor__C=c_param,
        regressor__max_iter=max_iter_param,
        regressor__tol=tol_param
    )


    cv = KFold(n_splits=5, shuffle=True, random_state=8)

    scores = cross_val_score(
        svm_pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring='neg_mean_absolute_error',
        n_jobs=-1,
        error_score='raise'
    )

    return np.mean(scores)

In [98]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, show_progress_bar=True, n_trials=10)

[I 2026-06-16 19:37:51,749] A new study created in memory with name: no-name-202a05d0-aef2-4764-871b-8b47cb0a0f6f

  0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-06-16 19:37:58,430] Trial 0 finished with value: -22.253472339686347 and parameters: {'regressor__max_iter': 8000, 'regressor__tol': 0.00021260897094455258, 'regressor__C': 0.26350117813004725}. Best is trial 0 with value: -22.253472339686347.
[I 2026-06-16 19:37:59,716] Trial 1 finished with value: -22.985212365337812 and parameters: {'regressor__max_iter': 9000, 'regressor__tol': 0.0061713378143223455, 'regressor__C': 0.04914189417397742}. Best is trial 0 with value: -22.253472339686347.
[I 2026-06-16 19:38:01,194] Trial 2 finished with value: -24.153725533037512 and parameters: {'regressor__max_iter': 1000, 'regressor__tol': 2.653959104351434e-05, 'regressor__C': 0.016068913324146106}. Best is trial 0 with value: -22.253472339686347.
[I 2026-06-16 19:38:02,448] Trial 3 finished with value: -24.78365415804842 and parameters: {'regressor__max_iter': 4000, 'regressor__tol': 0.0032177430938603187, 'regressor__C': 0.011313190611892005}. Best is trial 0 with value: -22.253472339686347.
[I 2026-06-16 19:39:29,056] Trial 4 finished with value: -22.08427232282851 and parameters: {'regressor__max_iter': 5000, 'regressor__tol': 2.494493358120867e-05, 'regressor__C': 11.727428371856595}. Best is trial 4 with value: -22.08427232282851.
[I 2026-06-16 19:39:30,890] Trial 5 finished with value: -22.534359667725816 and parameters: {'regressor__max_iter': 6000, 'regressor__tol': 0.002883282238536463, 'regressor__C': 0.10860573025302989}. Best is trial 4 with value: -22.08427232282851.
[I 2026-06-16 19:39:51,287] Trial 6 finished with value: -22.092171928497816 and parameters: {'regressor__max_iter': 7000, 'regressor__tol': 1.8039532997064275e-05, 'regressor__C': 2.522946733677244}. Best is trial 4 with value: -22.08427232282851.
[I 2026-06-16 19:39:53,183] Trial 7 finished with value: -22.290122215558714 and parameters: {'regressor__max_iter': 1000, 'regressor__tol': 0.0004096796869473953, 'regressor__C': 0.22475578591079395}. Best is trial 4 with value: -22.08427232282851.
[I 2026-06-16 19:39:55,044] Trial 8 finished with value: -25.84852276159802 and parameters: {'regressor__max_iter': 9000, 'regressor__tol': 0.00024258229568064618, 'regressor__C': 0.007324222053635457}. Best is trial 4 with value: -22.08427232282851.
[I 2026-06-16 19:39:56,399] Trial 9 finished with value: -41.777293760015276 and parameters: {'regressor__max_iter': 9000, 'regressor__tol': 7.643714814088808e-05, 'regressor__C': 0.00046326281757119026}. Best is trial 4 with value: -22.08427232282851.

In [99]:
study.trials_dataframe().to_csv('svmreg_results.csv')

In [100]:
best = study.best_params

In [102]:
# svm_pipeline.set_params(
#     regressor__C=best['regressor__C'],
#     regressor__max_iter=best['regressor__max_iter'],
#     regressor__tol=best['regressor__tol']
# )

In [103]:
# import importlib
# import ml_utils as mu

# # Эта команда принудительно обновит модуль в памяти Jupyter
# importlib.reload(mu)

In [104]:
# mu.run_experiment(svm_pipeline, 'svm', 'main_df_edited_no_dup.parquet', best)