# ИАД. Групповой проект. EDA. Предобработка данных

В данном ноутбуке находится предобработка данных датасета `hotel_bookings.csv`, а также информация о признаках, которые этот датасет содержит.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('hotel_bookings.csv')

In [ ]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

## Информация о датасете

* `hotel` - Тип отеля: `City Hotel` - городской отель, `Resort Hotel` - курортный отель
* `is_canceled` - Была ли бронь отменена: `1` = отменена, `0` = не отменена
* `lead_time` - Время между бронированием и заездом
* `arrival_date_year` - Год заезда
* `arrival_date_month` - Месяц заезда
* `arrival_date_week_number` - Номер недели заезда
* `arrival_date_day_of_month` - День месяца заезда
* `stays_in_weekend_nights` - Количество ночей на выходных
* `stays_in_week_nights` - Количество ночей в будние дни
* `adults` - Число взрослых гостей
* `children` - Число детей
* `babies` - Число младенцев

* `meal` - Тип питания: например, коды: `BB` = Bed & Breakfast (включен завтрак), `HB` = Half Board (полупансион), `FB` = Full Board (полный пансион), `SC` = Self Catering (питание не включено)

* `country` - Страна гостя: код страны, обычно в формате ISO-кода
* `market_segment` - Сегмент/источник бронирования: например, коды: `TA` = Travel Agent, `TO` = Tour Operator и др.

* `distribution_channel` - Канал распределения брони: например, коды: TA = Travel Agent, TO = Tour Operator

* `is_repeated_guest` - Повторный ли это гость: 1 = да, 0 = нет
* `previous_cancellations` - Сколько предыдущих броней отменялось  
* `previous_bookings_not_canceled` - Сколько предыдущих броней не отменялось  
* `reserved_room_type` - Зарезервированный тип номера: его код, например A, B, C и т. д.
* `assigned_room_type` - Фактически назначенный тип номера (аналогично `reserved_room_type`)

* `booking_changes` - Количество изменений брони  
* `deposit_type` - Тип депозита: `No Deposit` = без депозита, `Non Refund` = невозвратный, `Refundable` = возвратный
* `agent` - Код агента: идентификатор турагентства/агента
* `company` - Код компании: идентификатор компании, если бронь корпоративная
* `days_in_waiting_list` - Дней в списке ожидания  
* `customer_type` - Тип клиента: например, `Transient` = разовый клиент, `Transient-Party` = группа разовых клиентов, `Contract` = контрактный клиент, `Group` = групповая бронь
* `adr` - Average Daily Rate, средняя дневная ставка
* `required_car_parking_spaces` - Нужное число парковочных мест  
* `total_of_special_requests` - Общее число специальных запросов  
* `reservation_status` - Статус брони
* `reservation_status_date` - Дата статуса брони

##Разбор признаков датасета

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

###Количество объектов и признаков, а также их классификация по типам

In [ ]:
f"кол-во объектов: {len(df)}"

'кол-во объектов: 119390'

In [ ]:
f"кол-во признаков: {len(df.columns)}"

'кол-во признаков: 32'

In [ ]:
len(df[pd.isna(df.adr)])

0

####Работа с пропусками

Посчитаю долю нанов от общего количества объектов для каждого столбца.

In [ ]:
def nan_counts(df):
  nans = []
  for c in df.columns:
    nans.append(len(df[pd.isna(df[c])]))

  res = zip(list(df.columns), nans)
  return pd.dfFrame(res, columns = ['column', 'nan_count']).sort_values('nan_count', ascending=False)

In [ ]:
nan_counts(df).head(5)

                column  nan_count
24             company     112593
23               agent      16340
13             country        488
10            children          4
4   arrival_date_month          0

Так как признаки id турагентства/агента и id компании при корпоративной брони содержат много пропусков, будет логично убрать их из основной таблицы, перенеся часть исходного датасета с непустыми значениями этих признаков в отдельные таблицы соответственно.

In [ ]:
df_touragency_full = df[pd.isna(df.company)==False].copy()
df_corporate_tours = df[pd.isna(df.agent)==False].copy()

In [ ]:
df_touragency_full

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,No Deposit,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02
218,Resort Hotel,1,1,2015,July,28,8,0,1,2,...,No Deposit,NaN,110.0,0,Transient,104.72,0,1,Canceled,2015-07-08
219,Resort Hotel,1,1,2015,July,28,8,0,1,2,...,No Deposit,NaN,110.0,0,Transient,104.72,0,1,Canceled,2015-07-08
220,Resort Hotel,0,1,2015,July,28,8,0,2,2,...,No Deposit,NaN,110.0,0,Transient,104.72,1,1,Check-Out,2015-07-10
295,Resort Hotel,0,84,2015,July,28,11,1,1,2,...,No Deposit,NaN,113.0,0,Transient,100.00,1,0,Check-Out,2015-07-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119119,City Hotel,0,40,2017,August,35,29,0,1,1,...,No Deposit,NaN,451.0,0,Transient,95.00,0,0,Check-Out,2017-08-30
119122,City Hotel,0,40,2017,August,35,29,0,1,1,...,No Deposit,NaN,451.0,0,Transient,95.00,0,0,Check-Out,2017-08-30
119123,City Hotel,0,40,2017,August,35,29,0,1,1,...,No Deposit,NaN,451.0,0,Transient,95.00,0,0,Check-Out,2017-08-30
119124,City Hotel,0,0,2017,August,35,29,0,1,1,...,No Deposit,NaN,72.0,0,Transient,0.00,0,2,Check-Out,2017-08-30
119248,City Hotel,0,22,2017,August,35,29,0,3,1,...,No Deposit,NaN,485.0,0,Transient,75.00,0,4,Check-Out,2017-09-01

In [ ]:
df_corporate_tours

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.00,0,1,Canceled,2015-05-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [ ]:
del df['company'], df['agent']

In [ ]:
'agent' in df.columns

False

In [ ]:
'company' in df.columns

False

В остальных колонках просто очистим строки с пропусками.

In [ ]:
df.dropna(inplace=True)

In [ ]:
f"кол-во объектов: {len(df)}"

'кол-во объектов: 118898'

In [ ]:
f"кол-во признаков: {len(df.columns)}"

'кол-во признаков: 30'

###Работа с типами признаков в датасете

1. БИНАРНЫЕ ПРИЗНАКИ (0 или 1)
* `is_canceled` - бронь отменена или нет.

* `is_repeated_guest` - повторный гость или нет.

2. КАТЕГОРИАЛЬНЫЕ ПРИЗНАКИ

* `hotel` - тип отеля (City Hotel / Resort Hotel).

* `arrival_date_month` - месяц заезда (название месяца).

* `meal` - тип питания (BB, HB, FB, SC).

* `country` - ISO-код страны.

* `market_segment` - сегмент бронирования (TA, TO, Direct и т.д.).

* `distribution_channel` - канал дистрибуции (TA, TO, GDS и т.д.).

* `reserved_room_type` - забронированный тип номера (коды A, B, C...).

* `assigned_room_type` - фактически выданный тип номера.

* `deposit_type` - тип депозита (No Deposit, Non Refund, Refundable).

* `customer_type` - тип клиента (Transient, Group и т.д.).

* `reservation_status` - статус брони (Canceled, Check-Out, No-Show).

* `agent` - ID агента.

* `company` - ID компании.

3. КОЛИЧЕСТВЕННЫЕ ПРИЗНАКИ

Вещественные:

* `adr` - средняя цена за сутки.

Целочисленные:

* `lead_time` - количество дней между бронью и заездом.

* `stays_in_weekend_nights` - количество ночей.

* `stays_in_week_nights` - количество ночей.

* `adults` / `children` / `babies` - количество человек.

* `previous_cancellations` - количество отмен.

* `previous_bookings_not_canceled` - количество успешных броней.

* `booking_changes` - количество изменений в бронировании.

* `days_in_waiting_list` - количество дней в очереди.

* `total_of_special_requests` - количество спец. запросов.

4. ВРЕМЕННЫЕ/ПОРЯДКОВЫЕ ПРИЗНАКИ:

* `arrival_date_year` - год заезда.

* `arrival_date_week_number` - порядковый номер недели в году.

* `arrival_date_day_of_month` - день месяца.

* `reservation_status_date` - дата изменения статуса.

Приведем колонки к соответствующим им типам данных (колонки `company` и `agent` трогать не будем).

In [ ]:
cat_cols = [
    'hotel', 'arrival_date_month', 'meal', 'country',
    'market_segment', 'distribution_channel', 'reserved_room_type',
    'assigned_room_type', 'deposit_type', 'customer_type', 'reservation_status'
]

int_cols = [
    'lead_time', 'arrival_date_year', 'arrival_date_week_number',
    'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights',
    'adults', 'children', 'babies', 'previous_cancellations',
    'previous_bookings_not_canceled', 'booking_changes', 'days_in_waiting_list',
    'total_of_special_requests', 'is_canceled', 'is_repeated_guest'
]

float_cols = ['adr']

date_cols = ['reservation_status_date']

In [ ]:
for cat_col in cat_cols:
  df[cat_col] = df[cat_col].astype('category')

for int_col in int_cols:
  df[int_col] = df[int_col].astype('int')

for float_col in float_cols:
  df[float_col] = df[float_col].astype('float')

In [ ]:
df['reservation_status_date']

0         2015-07-01
1         2015-07-01
2         2015-07-02
3         2015-07-02
4         2015-07-03
             ...
119385    2017-09-06
119386    2017-09-07
119387    2017-09-07
119388    2017-09-07
119389    2017-09-07
Name: reservation_status_date, Length: 118898, dtype: object

In [ ]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

##Экспорт таблиц

In [ ]:
df.to_csv('main_df.csv')
df_corporate_tours.to_csv('df_corporate_tours.csv')
df_touragency_full.to_csv('df_touragency_full.csv')